include $(CURDIR)/../../lib/default.mk

###########################
#╔═══════════════════════╗#
#║ DOCUMENTATION ACTIONS ║#
#╚════════════════=══════╝#
###########################

project: ## Display project documentation
	glow $(GWD)/project/README.md

deployment: ## Display deployment documentation
	glow $(GWD)/deploy/README.md