name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
       
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build binaries for all platforms
      run: make build cross-platform 

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: Release
        owner: anotherhope
        tag: latest
        body: Release for FizzBuzz
        artifacts: ".build/bin/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}

    #- name: Run coverage
    #  run: go test -race -coverprofile=coverage.out -covermode=atomic
    #- name: Upload coverage to Codecov
    #  run: bash <(curl -s https://codecov.io/bash)

    #- name: Clean
    #  uses: dev-drprasad/delete-tag-and-release@v0.2.0
    #  with:
    #    delete_release: true
    #    tag_name: latest
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Release
    #  uses: ncipollo/release-action@v1
    #  with:
    #    name: Release
    #    owner: anotherhope
    #    tag: latest
    #    body: Release for FizzBuzz
    #    artifacts: ".build/bin/*"
    #    allowUpdates: true
    #    replacesArtifacts: true
    #    removeArtifacts: true
    #    token: ${{ secrets.GITHUB_TOKEN }}
